### ISSUE TITLE
website not reachable

### ISSUE THREAD

**Issue by websiteprojects123** [webguerilla/joomla-sitemapgenerator#13]
I am getting the below error message however the site is loading without any issue:

The generation of your sitemap failed with the error:
website not reachable.

**Comment by marcobeierer** [comment]
Hi @websiteprojects123 

Can you send me a link to your site so that I can have a closer look?

In the most such cases the Sitemap Generator is blocked by your robots.txt or a firewall.

**Comment by websiteprojects123** [comment]
Thanks for checking - is it secure for me to send the login details here?


Kind Regards


Felicity Selkirk
WEBSITE PROJECTS

(e) info@websiteprojects.com.au
(w) websiteprojects.com.au

(p) +61 414 691 444 (Aust + WhatsApp)
(p) +33 7 67 18 21 94 (France)
(s) felicity.selkirk

**Comment by marcobeierer** [comment]
Hi Felicity

No, this is public, but I also don't need your login details, just the URL of your site...

**Comment by websiteprojects123** [comment]
Please remove my site from the public post! Also I don’t want to post my client’s site publicly so please let me know how I can give you the URL privately.


Kind Regards


Felicity Selkirk
WEBSITE PROJECTS

(e) info@websiteprojects.com.au
(w) websiteprojects.com.au

(p) +61 414 691 444 (Aust + WhatsApp)
(p) +33 7 67 18 21 94 (France)
(s) felicity.selkirk

**Comment by marcobeierer** [comment]
I removed your site from the post, but you also have it in the signature of your posts... You also need to remove it there if you do not like to have your site public.

You can send me the URL of your clients website in private to email@marcobeierer.com

**Comment by marcobeierer** [comment]
solved by mail.
