### ISSUE TITLE
homepage don't open anymore

### ISSUE THREAD

**Issue by albi87** [webguerilla/joomla-sitemapgenerator#14]
Failed to start the session because headers have already been sent by "/homepages/37/d162076905/htdocs/clickandbuilds/Joomla/NeuAb090718/plugins/system/slider/slider.php" at line 1.

I get this since I started sitemap generator! pls help!

**Comment by marcobeierer** [comment]
Hi @albi87 

I'm not sure if this is caused by the Sitemap Generator. The error is caused in the slider plugin you are using. The Sitemap Generator just sets headers in the proxy requests but they are isolated.

Where do you get the error? In the frontend?
