### ISSUE TITLE
Plugin generates 0 urls in xml file

### ISSUE THREAD

**Issue by ituk** [webguerilla/joomla-sitemapgenerator#3]
Hey,
I clicked on "generate your sitemap", got no errors, but then when i open the generated xml I see no urls are listed: [see it here](http://www.luisa-tourguide.com/sitemap.xml).
my website is multilingual, so i tried activating the Multilanguage Support on the option page, but no change.

any suggestions?
Thanks,
Itamar

**Comment by marcobeierer** [comment]
Hi Itamar,

I had a look at your site and it looks like your server is blocking the Sitemap Generator.

I'm sorry, but there is nothing I can do about it. If you like to use the Sitemap Generator, you would have to contact your webhoster and ask them, if they can unblock the Sitemap Generator.

I think they block web bots in general and not just the Sitemap Generator.

Please let me know if you have further questions.

Best regards,
Marco

**Comment by ituk** [comment]
Thank you Marco, I'll have a look at it and come back to update.
