### ISSUE TITLE
How can I uninstall this plugin?

### ISSUE THREAD

**Issue by irinaelenaschmidt** [webguerilla/joomla-sitemapgenerator#4]
I don't seem to find it in the Plugins list...

**Comment by marcobeierer** [comment]
Hi Irina,

The Sitemap Generator is not a plugin, it's an component, which is installed as a package. You can uninstall it like any other component or package in the extension manager ("Extensions" -> "Manage" -> "Manage"). There search for "Sitemap Generator" and uninstall the package. If you uninstall the package, the component is uninstalled automatically.

Let me know if you have further questions.

Best regards,
Marco

**Comment by irinaelenaschmidt** [comment]
Thanks, Marco!

**Comment by marcobeierer** [comment]
Your welcome and have a nice day!
