### ISSUE TITLE
Site Map Pro 's Token ?

### ISSUE THREAD

**Issue by samranam** [webguerilla/joomla-sitemapgenerator#6]
I bought a Sitemap Generator pro subscription and you sent a token. I do not understand and can not make it work. Please explain.
Please answer quickly as I wrote an email to ask the question many time but still have not received any  answer.

Samran

**Comment by marcobeierer** [comment]
Hi Samran

Thank you for purchasing the Sitemap Generator and sorry for your trouble.

I answered your email yesterday at 9 o'clock PM. Have you not received it? Maybe in the spam folder?

To use the token you have to open the settings of the Sitemap Generator and there you could copy the token into the token field. Afterwards the token is automatically used. You don't need to install a new version of the component.

Please let me know if you have further questions.

Best regards,
Marco
