### ISSUE TITLE
SSL: no alternative certificate subject name matches target host name 'api.marcobeierer.com'.

### ISSUE THREAD

**Issue by erick-christian** [webguerilla/joomla-sitemapgenerator#7]
SSL: no alternative certificate subject name matches target host name 'api.marcobeierer.com'.

Hi, how can I fix this?

**Comment by erick-christian** [comment]
Full message is:

A cURL error occurred with the error message:
SSL: no alternative certificate subject name matches target host name 'api.marcobeierer.com'.

**Comment by marcobeierer** [comment]
Hi Erick

Thank you for your bug report. I have just enabled IPv6 support on the server. Could you tried it again and tell me if it works now?

If not, I would guess that it is a firewall issue on the client side as the certificate is fine.

Best regards
Marco
