### ISSUE TITLE
crawler not allowed by robots.txt.

### ISSUE THREAD

**Issue by DiGwork** [webguerilla/joomla-sitemapgenerator#8]
I get this error when using the site map generator:

The generation of your sitemap failed with the error:
The generation of your sitemap failed with the error:
crawler not allowed by robots.txt.

What now?

**Comment by marcobeierer** [comment]
You have to change your robots.txt file in the root of your Joomla installation so that the Sitemap Generator is allowed to access your site. The user agent of the Sitemap Generator is `MB-SitemapGenerator`.

If you need help with this, please send me the link to your site.

Best regards,
Marco
