### ISSUE TITLE
sitemap generator error

### ISSUE THREAD

**Issue by isdito** [webguerilla/joomla-sitemapgenerator#9]
Hello.

The sitemap give me a error. I reinstall but nothing, if you dont mind help me.

![captura](https://cloud.githubusercontent.com/assets/602151/24185580/2ba3a718-0ed4-11e7-8715-58b7ca84549d.jpg)

**Comment by marcobeierer** [comment]
Hi

It looks like your web hoster does not allow outgoing requests. There is sadly nothing I could do about it. You have to contact your web hoster and ask if it is possible to make outgoing requests to api.marcobeierer.com. Alternatively you could have a look if there is an appropriate setting in hosting control panel.

You could also [generate a sitemap on my website](https://www.marcobeierer.com/tools/sitemap-generator) and upload it manually, but that is not as comfortable as with the extension.

Best regards
Marco

**Comment by isdito** [comment]
Hello. 
I think that It is not posible the web hoster because I have the vps, in another page like http://www.fotografobodavalencia.es works and a few days ago in www.video-boda.es not works, but stay two years.

regards

**Comment by marcobeierer** [comment]
If it has worked before, maybe you or your hoster have changed something? If it is a VPS you could try to fetch https://api.marcobeierer.com on the command line with `wget` or `curl`. If you post the result here, I may could help you further.

**Comment by isdito** [comment]
But it is working in http://www.fotografobodavalencia.es in the same vps . Not works in www.video-boda.es

![Uploading Captura.jpg…]()

**Comment by isdito** [comment]
![captura](https://cloud.githubusercontent.com/assets/602151/24197816/79577a3c-0f03-11e7-9fcd-936c3a91bae9.jpg)

**Comment by marcobeierer** [comment]
Mmh, that looks fine. The domain is resolved to the correct IP. However the error in the Sitemap Generator indicates that this is not possible. But if the other site is on the same VPS, it has to be a Joomla related issue and not a server issue.

Do you have a firewall installed for the affected site?

**Comment by isdito** [comment]
Good morning.
Yes I have plesk, but if I have firewall for all why works in www.fotografobodavalencia.es and not works www.video-boda.es, not for a particular site. I think so.

.htcacces?? it is posible

**Comment by marcobeierer** [comment]
.htaccess is just for incoming requests, but the outgoing don't work.

Is Plesk configured per site? If so, maybe the sites have different configurations?

Otherwise, what extensions differ between the sites?

**Comment by isdito** [comment]
In this moment Star to work another time ;(((

**Comment by marcobeierer** [comment]
is it still working? then I could close the issue.

**Comment by isdito** [comment]
hello. Yes I execute in this moment to check.

**Comment by marcobeierer** [comment]
Thank you for your effort.

I just saw that another user from Spain had exactly the same issue last week. Maybe it was a temporary DNS issue...
